# Site settings
title: Flying
email: johnko5057@likesharing.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://flying.github.io/" # the base hostname & protocol for your site
twitter_username: johnko5057
github_username:  johnko5057

# Build settings
markdown: redcarpet
redcarpet:
  extensions: ["fenced_code_blocks", "tables"]
gems: [jekyll-paginate]
